# -*- coding: utf-8 -*-
"""
Create PPTX from template using slide master layouts.
Inherits design (colors, fonts, backgrounds) from template.

Usage:
    python scripts/create_from_template.py <template.pptx> <content.json> <output.pptx> [--config <layouts.json>]
    python scripts/create_from_template.py <template.pptx> --list-layouts

Options:
    --config <layouts.json>   Use pre-analyzed layout mapping file
                              (Generated by: python scripts/analyze_template.py <template.pptx>)

Supports image embedding:
    "image": {"path": "images/foo.png", "position": "right", "width_percent": 45}
    "image": {"url": "https://...", "position": "bottom", "height_percent": 50}

Examples:
    # Analyze template first (recommended):
    python scripts/analyze_template.py templates/sample-ppf.pptx

    # Then use the generated config:
    python scripts/create_from_template.py templates/sample-ppf.pptx content.json output.pptx --config templates/sample-ppf_layouts.json

    # Or let the script auto-detect layouts:
    python scripts/create_from_template.py templates/sample.pptx content.json output.pptx
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
import json
import sys
import argparse
import urllib.request
import tempfile
from pathlib import Path
from typing import Optional

# Base directory for resolving relative image paths (set in create_pptx_from_template)
BASE_DIR: Optional[Path] = None


def list_layouts(template_path: str) -> None:
    """List all slide layouts in the template with their placeholders."""
    prs = Presentation(template_path)
    
    print(f"\n{'='*60}")
    print(f"Template: {template_path}")
    print(f"Slide Size: {prs.slide_width.inches:.2f}\" x {prs.slide_height.inches:.2f}\"")
    print(f"{'='*60}\n")
    
    print(f"Found {len(prs.slide_masters)} slide master(s)\n")
    
    for master_idx, master in enumerate(prs.slide_masters):
        print(f"━━━ Slide Master {master_idx} ━━━")
        if master.name:
            print(f"    Name: {master.name}")
        print(f"    Layouts: {len(master.slide_layouts)}")
        print()
        
        for layout_idx, layout in enumerate(master.slide_layouts):
            print(f"  [{layout_idx}] {layout.name or '(unnamed)'}")
            
            # Show placeholders
            placeholders = []
            for shape in layout.placeholders:
                ph_type = str(shape.placeholder_format.type).replace('PLACEHOLDER_TYPE.', '')
                placeholders.append(f"{shape.placeholder_format.idx}:{ph_type}")
            
            if placeholders:
                print(f"      Placeholders: {', '.join(placeholders)}")
            else:
                print(f"      Placeholders: (none - blank layout)")
            print()
    
    # Show existing slides
    if prs.slides:
        print(f"━━━ Existing Slides ({len(prs.slides)}) ━━━")
        for slide_idx, slide in enumerate(prs.slides):
            layout_name = slide.slide_layout.name or '(unnamed)'
            print(f"  Slide {slide_idx + 1}: Layout = {layout_name}")
        print()
    
    print("Usage tip:")
    print('  In content.json, specify "layout": <index> to use a specific layout.')
    print('  Use "layout": 0 for title slides, "layout": 1 for content slides (typical).')
    print()


def find_placeholder(slide, ph_type_names: list):
    """Find a placeholder by type name(s)."""
    for shape in slide.placeholders:
        ph_type = str(shape.placeholder_format.type)
        for name in ph_type_names:
            if name in ph_type:
                return shape
    return None


def resolve_image_path(image_config: dict, content_path: str) -> Optional[str]:
    """
    Resolve image path from config. Supports local path or URL.
    Returns the resolved local file path (downloads URL if needed).
    """
    if 'url' in image_config:
        # Download from URL to temp file
        url = image_config['url']
        try:
            suffix = Path(url.split('?')[0]).suffix or '.png'
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
                print(f"    📥 Downloading image: {url[:50]}...")
                urllib.request.urlretrieve(url, tmp.name)
                return tmp.name
        except Exception as e:
            print(f"    [!] Failed to download image: {e}")
            return None
    elif 'path' in image_config:
        # Resolve local path
        path = image_config['path']
        base_dir = Path(content_path).parent.parent if content_path else Path('.')
        candidates = [
            base_dir / path,
            Path(path),
            Path(content_path).parent / path if content_path else None,
        ]
        for candidate in candidates:
            if candidate and candidate.exists():
                return str(candidate)
        print(f"    [!] Image not found: {path}")
        return None
    return None


def add_image_to_slide(slide, prs, image_config: dict, content_path: str) -> dict:
    """
    Add image to slide based on configuration.
    
    Args:
        slide: pptx slide object
        prs: Presentation object (for slide dimensions)
        image_config: {"path": ..., "position": "right|bottom|full", "width_percent": 45}
        content_path: Path to content.json for resolving relative paths
    
    Returns:
        Content area dict with adjusted dimensions, or None for full image
    """
    image_path = resolve_image_path(image_config, content_path)
    if not image_path:
        return {'left': Inches(0.5), 'top': Inches(1.5), 'width': Inches(12.333), 'height': Inches(5.5)}
    
    position = image_config.get('position', 'right')
    width_pct = image_config.get('width_percent', 45)
    height_pct = image_config.get('height_percent', 50)
    
    slide_width = prs.slide_width or Inches(13.333)
    slide_height = prs.slide_height or Inches(7.5)
    
    try:
        if position == 'full':
            # Full slide image (centered below title bar)
            img_left = Inches(0.5)
            img_top = Inches(1.5)
            img_width = Inches(12.333)
            slide.shapes.add_picture(image_path, img_left, img_top, width=img_width)
            return None  # No text area
            
        elif position == 'right':
            # Image on right, text on left
            img_width = Inches(13.333 * width_pct / 100)
            img_left = Inches(13.333 - 0.5) - img_width
            img_top = Inches(1.5)
            slide.shapes.add_picture(image_path, img_left, img_top, width=img_width)
            return {
                'left': Inches(0.5),
                'top': Inches(1.5),
                'width': Inches(13.333 * (100 - width_pct - 5) / 100),
                'height': Inches(5.5)
            }
            
        elif position == 'bottom':
            # Image at bottom, text on top
            text_height = Inches(7.5 * (100 - height_pct - 10) / 100)
            img_height = Inches(7.5 * height_pct / 100)
            img_top = Inches(7.5 - 0.5) - img_height
            img_left = Inches(0.5)
            slide.shapes.add_picture(image_path, img_left, img_top, height=img_height)
            return {
                'left': Inches(0.5),
                'top': Inches(1.5),
                'width': Inches(12.333),
                'height': text_height
            }
            
    except Exception as e:
        print(f"    [!] Failed to add image: {e}")
    
    # Default content area
    return {'left': Inches(0.5), 'top': Inches(1.5), 'width': Inches(12.333), 'height': Inches(5.5)}


def add_slide_from_layout(prs, layout_idx: int, title: str, items: Optional[list] = None, 
                          subtitle: Optional[str] = None, image_config: Optional[dict] = None,
                          content_path: Optional[str] = None) -> None:
    """Add a slide using the specified layout from the template, with optional image."""
    # Get layout (with fallback)
    try:
        layout = prs.slide_layouts[layout_idx]
    except IndexError:
        print(f"  Warning: Layout {layout_idx} not found, using layout 0")
        layout = prs.slide_layouts[0]
    
    slide = prs.slides.add_slide(layout)
    
    # Try to set title
    title_placeholder = find_placeholder(slide, ['TITLE', 'CENTER_TITLE'])
    if title_placeholder and title_placeholder.has_text_frame:
        title_placeholder.text_frame.paragraphs[0].text = title
    
    # Try to set subtitle (for title slides)
    if subtitle:
        subtitle_placeholder = find_placeholder(slide, ['SUBTITLE'])
        if subtitle_placeholder and subtitle_placeholder.has_text_frame:
            subtitle_placeholder.text_frame.paragraphs[0].text = subtitle
    
    # Add image if configured (before content, so image appears behind text if overlapping)
    content_area = None
    if image_config:
        content_area = add_image_to_slide(slide, prs, image_config, content_path)
        if content_area is None:
            # Full image slide - skip content
            return slide
    
    # Try to set content/body
    if items:
        body_placeholder = find_placeholder(slide, ['BODY', 'OBJECT', 'CONTENT'])
        if body_placeholder and body_placeholder.has_text_frame:
            tf = body_placeholder.text_frame
            tf.clear()  # Clear existing content
            
            for i, item in enumerate(items):
                if i > 0:
                    p = tf.add_paragraph()
                else:
                    p = tf.paragraphs[0] if tf.paragraphs else tf.add_paragraph()
                
                # Handle different item formats
                if isinstance(item, dict):
                    p.text = item.get('text', str(item))
                    p.level = item.get('level', 0)
                else:
                    p.text = str(item)
                    p.level = 0
        else:
            # Fallback: add textbox if no body placeholder
            # Use adjusted content_area if image was added
            if content_area:
                content_box = slide.shapes.add_textbox(
                    content_area['left'], content_area['top'],
                    content_area['width'], content_area['height']
                )
            else:
                content_box = slide.shapes.add_textbox(
                    Inches(0.5), Inches(1.5), 
                    prs.slide_width - Inches(1), Inches(5.5)
                )
            tf = content_box.text_frame
            tf.word_wrap = True
            
            for i, item in enumerate(items):
                if i > 0:
                    p = tf.add_paragraph()
                else:
                    p = tf.paragraphs[0]
                
                if isinstance(item, dict):
                    p.text = f"• {item.get('text', str(item))}"
                else:
                    p.text = f"• {str(item)}"
                p.font.size = Pt(18)
    
    return slide


def validate_and_fix_content(slides_data: list, strict: bool = False) -> tuple[list, bool]:
    """
    Validate content and auto-fix common issues.
    - closing type with items → convert to content type
    - title type with items → keep items (subtitle might also exist)
    - content/agenda slides without items → ERROR (strict mode) or WARNING
    
    Args:
        slides_data: List of slide data dictionaries
        strict: If True, raise error on critical issues (empty content slides)
    
    Returns:
        tuple: (fixed slides_data, has_errors)
    """
    fixed_count = 0
    errors = []
    warnings = []
    
    for i, slide in enumerate(slides_data):
        slide_type = slide.get('type', 'content')
        # Support multiple content key names: items, content, bullets
        items = slide.get('items', slide.get('content', slide.get('bullets', [])))
        title = slide.get('title', f'Slide {i + 1}')
        
        # Check: closing type should not have multiple items
        if slide_type == 'closing' and items and len(items) > 1:
            warnings.append(f"  [!] Warning: Slide {i + 1} '{title[:30]}...' has type='closing' with {len(items)} items")
            warnings.append(f"      → Auto-converting to type='content' (closing is for short endings only)")
            slide['type'] = 'content'
            fixed_count += 1
        
        # Check: agenda type should have items
        if slide_type == 'agenda' and not items:
            warnings.append(f"  [!] Warning: Slide {i + 1} '{title[:30]}...' has type='agenda' but no items")
        
        # CRITICAL: content slides must have items
        if slide_type == 'content' and not items:
            errors.append(f"  [X] ERROR: Slide {i + 1} '{title[:30]}...' has type='content' but NO CONTENT!")
            errors.append(f"      Check if 'items', 'content', or 'bullets' key exists in JSON")
        
        # Check: title type with many items might be better as content
        if slide_type == 'title' and items and len(items) > 2:
            warnings.append(f"  ℹ️  Note: Slide {i + 1} '{title[:30]}...' has type='title' with {len(items)} items")
            warnings.append(f"      Consider using type='content' for better display")
    
    # Print warnings
    for w in warnings:
        print(w)
    
    # Print errors
    for e in errors:
        print(e)
    
    if fixed_count > 0:
        print(f"\n  ✅ Auto-fixed {fixed_count} slide(s)")
    
    has_errors = len(errors) > 0
    if has_errors:
        print(f"\n  [!] Found {len(errors) // 2} critical error(s)!")
        if strict:
            print(f"  [?] Hint: content.json may use wrong key name (try 'items' or 'bullets')")
    
    print()
    return slides_data, has_errors


def create_pptx_from_template(template_path: str, content_path: str, output_path: str, config_path: Optional[str] = None, force: bool = False) -> None:
    """Create a new PPTX from template and content JSON."""
    
    # Load template
    print(f"\nLoading template: {template_path}")
    prs = Presentation(template_path)
    
    # Show layout info
    print(f"\n{'─'*50}")
    print("Available Layouts:")
    for idx, layout in enumerate(prs.slide_layouts):
        print(f"  [{idx}] {layout.name or '(unnamed)'}")
    print(f"{'─'*50}\n")
    
    # Remove existing slides (start fresh with just the master)
    while len(prs.slides) > 0:
        rId = prs.slides._sldIdLst[0].rId
        prs.part.drop_rel(rId)
        del prs.slides._sldIdLst[0]
    print("Cleared existing slides from template.\n")
    
    # Load content
    print(f"Loading content: {content_path}")
    with open(content_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    slides_data = data.get('slides', data) if isinstance(data, dict) else data
    if isinstance(slides_data, dict):
        slides_data = [slides_data]
    
    # Validate and auto-fix content issues
    print("[*] Validating content...")
    slides_data, has_critical_errors = validate_and_fix_content(slides_data)
    
    if has_critical_errors and not force:
        print("\n[!] CRITICAL: Content validation failed!")
        print("   Found slides with type='content' but no items/bullets.")
        print("   Please fix the content.json before generating PPTX.")
        print("   (Use --force to ignore this check)")
        sys.exit(1)
    elif has_critical_errors and force:
        print("\n[!] WARNING: Content validation found issues but continuing due to --force flag.")
    
    print(f"Creating {len(slides_data)} slides...\n")
    
    # Load layout mapping from config file if provided
    layout_map = None
    if config_path and Path(config_path).exists():
        print(f"📋 Using layout config: {config_path}")
        with open(config_path, 'r', encoding='utf-8') as f:
            config = json.load(f)
        layout_map = config.get('layout_mapping', {})
        print(f"   Loaded mappings: {list(layout_map.keys())}\n")
    
    # Auto-detect layouts if no config provided
    if not layout_map:
        print("[*] Auto-detecting layouts from template names...")
        
        # Smart layout detection - find best matching layout by name
        def find_layout_by_keywords(layouts, keywords: list, fallback: int = 0) -> int:
            """Find layout index by matching keywords in layout name."""
            for keyword in keywords:
                for idx, layout in enumerate(layouts):
                    name = (layout.name or '').lower()
                    if keyword.lower() in name:
                        return idx
            return fallback
        
        # Detect layout indices based on template
        title_layout = find_layout_by_keywords(prs.slide_layouts, 
            ['title slide', 'タイトル スライド', 'タイトルスライド'], 0)
        content_layout = find_layout_by_keywords(prs.slide_layouts, 
            ['title and content', 'タイトルとコンテンツ', 'content'], 1)
        section_layout = find_layout_by_keywords(prs.slide_layouts, 
            ['section title', 'section', 'セクション'], content_layout)
        agenda_layout = find_layout_by_keywords(prs.slide_layouts, 
            ['agenda', 'アジェンダ'], content_layout)
        closing_layout = find_layout_by_keywords(prs.slide_layouts, 
            ['closing', 'クロージング', 'end'], section_layout)
        
        layout_map = {
            'title': title_layout,
            'content': content_layout,
            'section': section_layout,
            'section_title': section_layout,
            'two_content': content_layout,
            'two_column': content_layout,
            'comparison': content_layout,
            'blank': content_layout,
            'agenda': agenda_layout,
            'summary': content_layout,      # まとめ → コンテンツスタイル
            'next_steps': content_layout,   # 今後のステップ
            'feature': content_layout,
            'closing': closing_layout,      # 最終スライド → クロージング
            'code': content_layout,
            'photo': content_layout,
        }
        
        print(f"   Auto-detected: title={title_layout}, content={content_layout}, section={section_layout}, agenda={agenda_layout}, closing={closing_layout}\n")
        print("[?] Tip: Run 'python scripts/analyze_template.py <template.pptx>' for accurate layout mapping.\n")
    
    # Create slides
    for i, slide_data in enumerate(slides_data):
        slide_type = slide_data.get('type', 'content')
        title = slide_data.get('title', f'Slide {i + 1}')
        # Support multiple content key names: items, content, bullets
        items = slide_data.get('items', slide_data.get('content', slide_data.get('bullets', [])))
        subtitle = slide_data.get('subtitle', '')
        
        # Determine layout index (priority: slide.layout > layout_map > fallback)
        layout_idx = slide_data.get('layout')
        if layout_idx is None:
            layout_idx = layout_map.get(slide_type, layout_map.get('content', 1))
        
        # Ensure layout_idx is valid
        if layout_idx is None:
            layout_idx = 1
        layout_idx = min(layout_idx, len(prs.slide_layouts) - 1)
        
        layout_name = prs.slide_layouts[layout_idx].name or '(unnamed)'
        
        # Get optional image configuration
        image_config = slide_data.get('image')
        if image_config:
            print(f"  Slide {i + 1}: {title[:40]}... [Layout {layout_idx}: {layout_name}] 📷")
        else:
            print(f"  Slide {i + 1}: {title[:40]}... [Layout {layout_idx}: {layout_name}]")
        
        add_slide_from_layout(prs, layout_idx, title, items, subtitle, image_config, content_path)
    
    # Save
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    prs.save(output_path)
    print(f"\n✅ Created: {output_path}")
    print(f"   Total slides: {len(prs.slides)}")


def main():
    parser = argparse.ArgumentParser(
        description='Create PPTX from template using slide master layouts.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  # List available layouts in template:
  python scripts/create_from_template.py templates/sample.pptx --list-layouts

  # Analyze template and generate config (recommended):
  python scripts/analyze_template.py templates/sample-ppf.pptx

  # Create PPTX with layout config:
  python scripts/create_from_template.py templates/sample-ppf.pptx content.json output.pptx \\
      --config templates/sample-ppf_layouts.json

  # Auto-detect layouts (no config):
  python scripts/create_from_template.py templates/sample.pptx content.json output.pptx
'''
    )
    
    parser.add_argument('template', help='Path to template PPTX file')
    parser.add_argument('content', nargs='?', help='Path to content JSON file')
    parser.add_argument('output', nargs='?', help='Path to output PPTX file')
    parser.add_argument('--config', '-c', help='Path to layout config JSON (from analyze_template.py)')
    parser.add_argument('--list-layouts', '-l', action='store_true', help='List available layouts and exit')
    parser.add_argument('--force', '-f', action='store_true', help='Force generation even if validation fails')
    
    args = parser.parse_args()
    
    # List layouts mode
    if args.list_layouts or not args.content:
        list_layouts(args.template)
        return
    
    # Validate arguments
    if not args.output:
        parser.error("Output path is required")
    
    # Auto-find config if not specified
    config_path = args.config
    if not config_path:
        # Try to find matching config file
        template_stem = Path(args.template).stem
        auto_config = Path(f"templates/{template_stem}_layouts.json")
        if auto_config.exists():
            config_path = str(auto_config)
            print(f"[+] Auto-found config: {config_path}")
    
    create_pptx_from_template(args.template, args.content, args.output, config_path, force=args.force)


if __name__ == '__main__':
    main()
